---
title: Galada Theme | Theme for Jekyll
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Galada is an easy and simple theme for Jekyll. Dark colors, give it a
  special exquisite look. A careful approach to design and features make it an ideal
  solution for a personal blog.
baseurl: "/galada"
url: ''
author-name: Natali Anderson
author-avatar: '09.jpg'
facebook: https://facebook.com/
twitter: https://twitter.com/
instagram: https://www.instagram.com/
pinterest: https://www.pinterest.com/
disqus-identifier: mr-brown
instafeed: true
google-analytics: 
mailchimp: 
markdown: kramdown
permalink: ":title/"
plugins:
- jekyll-paginate
- jekyll-sitemap
paginate: 7
paginate_path: "/page/:num"
include:
- _pages
sass:
  sass_dir: _sass
  style: compressed
